"""
Application-wide constants to eliminate magic numbers and strings.
"""

PIPELINE_STAGES = ["NEW", "PITCHED", "INTERESTED", "REPLIED", "CONVERTED", "CLOSED", "IGNORED"]
PRIORITY_LEVELS = ["HIGH", "MEDIUM", "LOW", "IGNORE"]
PRIORITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2, "IGNORE": 3}

# Search and scraping configurations
MAX_SEARCH_RESULTS = 100
MAX_DEEP_SCAN_ZONES = 10
SERP_RESULTS_PER_PAGE = 20
SERP_RATE_LIMIT_SECONDS = 1

# Website checking configurations
WEBSITE_CHECK_MAX_WORKERS = 5
WEBSITE_CHECK_TIMEOUT = 15
WEBSITE_CHECK_MAX_SITES = 20

# Cleanup retention
CLEANUP_UNCONTACTED_DAYS = 14
CLEANUP_IGNORED_DAYS = 7
CLEANUP_HISTORY_DAYS = 30

# Authentication configurations
SESSION_LIFETIME_SECONDS = 86400
LOGIN_MAX_ATTEMPTS = 5
LOGIN_LOCKOUT_SECONDS = 300
