"""Initial schema

Revision ID: f7786b33d913
Revises: 
Create Date: 2026-06-13 22:05:01.983751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7786b33d913'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drip_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delay_days', sa.Integer(), server_default='3', nullable=True),
    sa.Column('max_followups', sa.Integer(), server_default='2', nullable=True),
    sa.Column('followup_subject', sa.String(length=255), server_default='Quick follow up regarding proposal', nullable=True),
    sa.Column('followup_template', sa.Text(), server_default='', nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('imap_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), server_default='993', nullable=True),
    sa.Column('imap_email', sa.String(length=255), nullable=False),
    sa.Column('imap_password_encrypted', sa.Text(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=True),
    sa.Column('address', sa.Text(), server_default='', nullable=True),
    sa.Column('website', sa.Text(), server_default='', nullable=True),
    sa.Column('rating', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=True),
    sa.Column('category', sa.String(length=255), server_default='', nullable=True),
    sa.Column('city', sa.String(length=255), server_default='', nullable=True),
    sa.Column('priority', sa.String(length=50), server_default='LOW', nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), server_default='', nullable=True),
    sa.Column('source', sa.String(length=100), server_default='google_maps', nullable=True),
    sa.Column('contacted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('contact_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=True),
    sa.Column('instagram', sa.String(length=255), server_default='', nullable=True),
    sa.Column('facebook', sa.String(length=255), server_default='', nullable=True),
    sa.Column('custom_pitch', sa.Text(), server_default='', nullable=True),
    sa.Column('is_broken_website', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('line_type', sa.String(length=100), server_default='', nullable=True),
    sa.Column('pipeline_stage', sa.String(length=100), server_default='NEW', nullable=True),
    sa.Column('email', sa.String(length=255), server_default='', nullable=True),
    sa.Column('remind_date', sa.Date(), nullable=True),
    sa.Column('remind_status', sa.String(length=100), server_default='', nullable=True),
    sa.Column('audit_data', sa.Text(), server_default='', nullable=True),
    sa.Column('drip_sequence_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('last_followup_date', sa.DateTime(), nullable=True),
    sa.Column('followup_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'user_id', name='leads_place_id_user_id_key')
    )
    op.create_index('idx_leads_drip', 'leads', ['drip_sequence_active', 'pipeline_stage'], unique=False)
    op.create_index('idx_leads_remind', 'leads', ['remind_status', 'remind_date'], unique=False)
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_contacted'), 'leads', ['contacted'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_pipeline_stage'), 'leads', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('results_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('leads_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('searched_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('deep_scan', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('zones', sa.Text(), server_default='', nullable=True),
    sa.Column('include_with_website', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('hide_saved', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_searched_at'), 'search_history', ['searched_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('smtp_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), server_default='465', nullable=True),
    sa.Column('smtp_email', sa.String(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('template_used', sa.String(length=255), server_default='', nullable=True),
    sa.Column('message_sent', sa.Text(), server_default='', nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('opened', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('clicked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('clicked_links', sa.Text(), server_default='', nullable=True),
    sa.Column('is_reply', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('reply_body', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_is_reply'), 'message_log', ['is_reply'], unique=False)
    op.create_index(op.f('ix_message_log_lead_id'), 'message_log', ['lead_id'], unique=False)
    op.create_index(op.f('ix_message_log_user_id'), 'message_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_log_user_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_lead_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_is_reply'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_table('smtp_settings')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_searched_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_pipeline_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_contacted'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_index('idx_leads_remind', table_name='leads')
    op.drop_index('idx_leads_drip', table_name='leads')
    op.drop_table('leads')
    op.drop_table('imap_settings')
    op.drop_table('drip_configurations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
