import requests
import json

class AIOutreachWriter:
    @staticmethod
    def generate_pitch(lead_data: dict, project_sample: str, api_key: str) -> str:
        """
        Generates a highly personalized, human-like sales pitch using the Gemini API.
        Uses raw requests to avoid installing extra dependencies.
        """
        if not api_key:
            raise Exception("Gemini API key is required for AI generation.")

        # Build the prompt with an elite system persona
        prompt = f"""
You are an Elite Business Development Consultant, Growth Hacker, and Modern Web Designer in India who helps local businesses double their customers using stunning, fast web portals and digital storefronts.

Write a highly personalized, extremely conversational, and premium sales pitch for the following business:
- Business Name: {lead_data.get('name', 'Business')}
- Category: {lead_data.get('category', 'Business')}
- Location: {lead_data.get('city', 'your city')}
- Google Maps Rating: {lead_data.get('rating', '0')}
- Google Maps Reviews: {lead_data.get('reviews', '0')}
- Website: They DO NOT have a website yet (Huge gap!).

Best matching project proof to naturally mention:
{project_sample}

CRITICAL COPYWRITING DIRECTIVES (FOLLOW THOROUGHLY):
1. CASUAL GREETING: NEVER start with robotic or formal things like "नमस्ते {lead_data.get('name')} Team! 👋" or "प्रिय S Salon". Instead, use extremely natural, friendly greetings like "Hey {lead_data.get('name')} team! 👋" or "Hey there! Quick question for the team at {lead_data.get('name')}."
2. IMPRESSION OVER FLATTERY: Do NOT write generic praise like "Aapka review dekh kar mujhe bahut khushi hui." That sounds fake and robotic. Instead, say something exciting and real like:
   "Google par aapke *{lead_data.get('rating')} rating* aur *{lead_data.get('reviews')} reviews* dekhe—sach mein kamaal ka response hai! {lead_data.get('city', 'your city')} mein log aapki service ko sach mein bahut pasand kar rahe hain. 🔥"
3. THE GAP (CONVERSATIONAL PAIN POINT): Pivot smoothly. Explain that when high-paying clients look for the best salons/services in their area, they expect an interactive digital booking experience or digital gallery, and not having a website means losing premium clients.
   E.g., "But ek choti si opportunity miss ho rahi hai—Google search par aapki koi interactive booking site ya digital storefront nahi mili. Aajkal 70%+ premium customers direct list dekh kar online bookings kar lete hain, aur website na hone se ye direct bookings competitors ke paas ja rahi hain."
4. THE SOCIAL PROOF: Incorporate the provided portfolio work sample sentence naturally. The portfolio sample is already a complete, conversational sentence describing our work (e.g., "maine haal hi mein ek GYM website banayi hai..."). Simply integrate it smoothly as its own short paragraph, or weave it in with a simple transition.
   E.g., "{project_sample}"
5. HIGH-VALUE CALL TO ACTION (CTA): Make the offer absolutely irresistible and low-friction. Instead of asking for a boring call, offer a free draft/mockup!
   E.g., "Maine aapke business details ke sath ek *chota sa premium homepage mockup / raw design layout* sketch kiya hai. Kya main uska ek quick link ya screen recording video yahan share karu? Koi charges nahi hain, just wanted to show you what's possible! Let me know if that sounds good."
6. FORMATTING & TONE:
   - Language must be ultra-premium, modern, natural Hinglish (how young entrepreneurs talk on WhatsApp).
   - Use 3-4 very short paragraphs. Break lines to make it easy to read on mobile.
   - Use bold text for key numbers and phrases using asterisks (e.g., *4.8 rating*, *70%+ premium customers*, *free mockup design*).
   - Keep emojis limited to 3 or 4 maximum (e.g. 👋, 🔥, 📈, 💬). No emoji spam.
   - NO PLACEHOLDERS: Final output must contain absolutely NO brackets, no [Your Name], no [Insert Link], etc. Output must be 100% ready to copy-paste.

---------------------------------
GOLD STANDARD EXAMPLE (Mirror this exact tone, style, vocabulary, and structural flow):

Target Business: "Shiva Café N' Restro" in Bhopal with 4.7 stars and 320 reviews.
Project Sample: "maine haal hi mein ek Hotel/Restaurant website banayi hai, aap is link par demo dekh sakte hain: https://raunaksharmaq64.github.io/portfolio/restaurant"

Perfect Pitch Output generated by you:
Hey Shiva Café N' Restro team! 👋 

Google par aapke *4.7 rating* aur *320+ reviews* dekhe—sach mein Bhopal mein aap logo ka food aur brand value next level hai! People are absolutely loving your place. 🔥 

Maine notice kiya ki Google par search karne par aapki koi professional website ya interactive digital menu link nahi mil raha hai. Aajkal mostly customers online menu aur tables book karna chahte hain, aur site na hone ki wajah se 30-40% direct premium orders and table reservations competitors ke paas divert ho jati hain.

Maine haal hi mein ek similar premium brand ke liye ek digital storefront build kiya tha, aap is link par live demo dekh sakte hain: maine haal hi mein ek Hotel/Restaurant website banayi hai, aap is link par demo dekh sakte hain: https://raunaksharmaq64.github.io/portfolio/restaurant

Aapke café ke details ke sath maine ek *chota sa premium homepage mockup design layout* sketch kiya hai (just to show you a fresh idea). Kya main uska ek quick link ya screen recording video share karu yahan? 

No commitments at all, strictly for you to look. Let me know if that sounds good! 💬
---------------------------------
"""

        # 1. Quick validation: Google API Keys ALWAYS start with "AIza"
        if not api_key.startswith("AIza"):
            raise Exception("Invalid Gemini API Key format. Google API keys must start with 'AIza' (e.g. 'AIzaSy...'). Please make sure you copied the correct key from Google AI Studio and did not paste your SerpApi key here.")

        # 2. Dynamic Model Discovery: Ask Google what models this key supports!
        discovered_models = []
        try:
            print("Querying Google for available models...")
            list_url = f"https://generativelanguage.googleapis.com/v1/models?key={api_key}"
            res = requests.get(list_url, timeout=10)
            
            if res.status_code == 200:
                models_data = res.json().get("models", [])
                for m in models_data:
                    name = m.get("name", "")
                    methods = m.get("supportedGenerationMethods", [])
                    if "generateContent" in methods:
                        # Extract short name (e.g. "models/gemini-1.5-flash" -> "gemini-1.5-flash")
                        model_id = name.split("/")[-1] if "/" in name else name
                        discovered_models.append(("v1", model_id))
                print(f"Dynamically discovered models: {discovered_models}")
        except Exception as list_err:
            print(f"Model discovery query failed: {list_err}. Falling back to default list.")

        # 3. Compile final models list to try (discovered models first, then hardcoded fallbacks)
        models_to_try = discovered_models + [
            ("v1", "gemini-1.5-flash"),
            ("v1beta", "gemini-1.5-flash"),
            ("v1beta", "gemini-1.5-flash-latest"),
            ("v1", "gemini-1.5-pro"),
            ("v1beta", "gemini-pro")
        ]

        # Remove duplicates while preserving order
        seen = set()
        final_models = []
        for ver, mod in models_to_try:
            if (ver, mod) not in seen:
                seen.add((ver, mod))
                final_models.append((ver, mod))

        last_error = ""
        for version, model in final_models:
            url = f"https://generativelanguage.googleapis.com/{version}/models/{model}:generateContent?key={api_key}"
            headers = {
                "Content-Type": "application/json"
            }
            payload = {
                "contents": [
                    {
                        "parts": [
                            {"text": prompt}
                        ]
                    }
                ],
                "generationConfig": {
                    "temperature": 0.7,
                    "maxOutputTokens": 800
                }
            }

            try:
                print(f"Trying Gemini model: {model} on {version}...")
                response = requests.post(url, headers=headers, json=payload, timeout=12)
                
                if response.status_code == 200:
                    data = response.json()
                    candidates = data.get("candidates", [])
                    if candidates:
                        text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                        if text:
                            print(f"Success with Gemini model: {model}!")
                            return text.strip()
                
                # Fetch detailed error response if available
                try:
                    error_data = response.json()
                    last_error = error_data.get("error", {}).get("message", f"Status {response.status_code}")
                except:
                    last_error = f"Status {response.status_code}"
                print(f"Model {model} on {version} failed: {last_error}")
                
            except requests.exceptions.Timeout:
                last_error = "Request timed out."
                print(f"Model {model} timed out.")
            except Exception as e:
                last_error = str(e)
                print(f"Network error with model {model}: {last_error}")

        # Check if the error is the common Google Cloud "API not enabled" or "Not found/supported" issue
        if "not found for API version" in last_error or "not supported for generateContent" in last_error:
            raise Exception(
                "Your API key is a valid Google Cloud key, but the Gemini API (Generative Language API) "
                "is not enabled or is restricted for this key.\n\n"
                "To fix this, please do ONE of the following:\n"
                "1. [RECOMMENDED] Go to Google AI Studio (https://aistudio.google.com/), click 'Get API key', and create a new key. Keys created in AI Studio have Gemini enabled automatically.\n"
                "2. If you created this key in the Google Cloud Console: Go to your Google Cloud Console project, search for the 'Generative Language API' in the API Library, and click 'Enable'. Also, ensure that any API restrictions on your API key under 'Credentials' allow the 'Generative Language API'."
            )

        raise Exception(f"All Gemini models failed. Last error: {last_error}")
